### ISSUE TITLE
Question: Where is the "high-level interface for importing from Keras/TensorFlow"?

### ISSUE THREAD

**Issue by wemyss** [tensorfire/tensorfire#1]
Hey! Thanks for making this awesome project, the demos are really cool! 👍 

At the beginning of the readme it mentions this, however searching around I've only found documents/examples of the low level api. Is the high level api still being developed or is there somewhere I can find it documented?

**Comment by antimatter15** [comment]
The high level API is implemented in the examples/keras folder (https://github.com/tensorfire/tensorfire/tree/master/demos/keras). 

It's not currently really being developed, so I'd probably recommend using Tensorflow.JS (https://js.tensorflow.org/)

**Comment by wemyss** [comment]
Thank you! Just saw the latest commit was over 4 months ago and was going to ask that 😅. Have a good day!

**Comment by EddieOne** [comment]
Will you update the website? A lot of people will search there first.
